// Code generated by protoc-gen-go-pulsar. DO NOT EDIT.
package egvmod

import (
	fmt "fmt"
	runtime "github.com/cosmos/cosmos-proto/runtime"
	_ "github.com/cosmos/gogoproto/gogoproto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoiface "google.golang.org/protobuf/runtime/protoiface"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	io "io"
	reflect "reflect"
	sync "sync"
)

var (
	md_OperatorTrxCounter           protoreflect.MessageDescriptor
	fd_OperatorTrxCounter_operator  protoreflect.FieldDescriptor
	fd_OperatorTrxCounter_trx_count protoreflect.FieldDescriptor
)

func init() {
	file_chikku_egvmod_trxcounter_proto_init()
	md_OperatorTrxCounter = File_chikku_egvmod_trxcounter_proto.Messages().ByName("OperatorTrxCounter")
	fd_OperatorTrxCounter_operator = md_OperatorTrxCounter.Fields().ByName("operator")
	fd_OperatorTrxCounter_trx_count = md_OperatorTrxCounter.Fields().ByName("trx_count")
}

var _ protoreflect.Message = (*fastReflection_OperatorTrxCounter)(nil)

type fastReflection_OperatorTrxCounter OperatorTrxCounter

func (x *OperatorTrxCounter) ProtoReflect() protoreflect.Message {
	return (*fastReflection_OperatorTrxCounter)(x)
}

func (x *OperatorTrxCounter) slowProtoReflect() protoreflect.Message {
	mi := &file_chikku_egvmod_trxcounter_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

var _fastReflection_OperatorTrxCounter_messageType fastReflection_OperatorTrxCounter_messageType
var _ protoreflect.MessageType = fastReflection_OperatorTrxCounter_messageType{}

type fastReflection_OperatorTrxCounter_messageType struct{}

func (x fastReflection_OperatorTrxCounter_messageType) Zero() protoreflect.Message {
	return (*fastReflection_OperatorTrxCounter)(nil)
}
func (x fastReflection_OperatorTrxCounter_messageType) New() protoreflect.Message {
	return new(fastReflection_OperatorTrxCounter)
}
func (x fastReflection_OperatorTrxCounter_messageType) Descriptor() protoreflect.MessageDescriptor {
	return md_OperatorTrxCounter
}

// Descriptor returns message descriptor, which contains only the protobuf
// type information for the message.
func (x *fastReflection_OperatorTrxCounter) Descriptor() protoreflect.MessageDescriptor {
	return md_OperatorTrxCounter
}

// Type returns the message type, which encapsulates both Go and protobuf
// type information. If the Go type information is not needed,
// it is recommended that the message descriptor be used instead.
func (x *fastReflection_OperatorTrxCounter) Type() protoreflect.MessageType {
	return _fastReflection_OperatorTrxCounter_messageType
}

// New returns a newly allocated and mutable empty message.
func (x *fastReflection_OperatorTrxCounter) New() protoreflect.Message {
	return new(fastReflection_OperatorTrxCounter)
}

// Interface unwraps the message reflection interface and
// returns the underlying ProtoMessage interface.
func (x *fastReflection_OperatorTrxCounter) Interface() protoreflect.ProtoMessage {
	return (*OperatorTrxCounter)(x)
}

// Range iterates over every populated field in an undefined order,
// calling f for each field descriptor and value encountered.
// Range returns immediately if f returns false.
// While iterating, mutating operations may only be performed
// on the current field descriptor.
func (x *fastReflection_OperatorTrxCounter) Range(f func(protoreflect.FieldDescriptor, protoreflect.Value) bool) {
	if x.Operator != "" {
		value := protoreflect.ValueOfString(x.Operator)
		if !f(fd_OperatorTrxCounter_operator, value) {
			return
		}
	}
	if x.TrxCount != int64(0) {
		value := protoreflect.ValueOfInt64(x.TrxCount)
		if !f(fd_OperatorTrxCounter_trx_count, value) {
			return
		}
	}
}

// Has reports whether a field is populated.
//
// Some fields have the property of nullability where it is possible to
// distinguish between the default value of a field and whether the field
// was explicitly populated with the default value. Singular message fields,
// member fields of a oneof, and proto2 scalar fields are nullable. Such
// fields are populated only if explicitly set.
//
// In other cases (aside from the nullable cases above),
// a proto3 scalar field is populated if it contains a non-zero value, and
// a repeated field is populated if it is non-empty.
func (x *fastReflection_OperatorTrxCounter) Has(fd protoreflect.FieldDescriptor) bool {
	switch fd.FullName() {
	case "chikku.egvmod.OperatorTrxCounter.operator":
		return x.Operator != ""
	case "chikku.egvmod.OperatorTrxCounter.trx_count":
		return x.TrxCount != int64(0)
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: chikku.egvmod.OperatorTrxCounter"))
		}
		panic(fmt.Errorf("message chikku.egvmod.OperatorTrxCounter does not contain field %s", fd.FullName()))
	}
}

// Clear clears the field such that a subsequent Has call reports false.
//
// Clearing an extension field clears both the extension type and value
// associated with the given field number.
//
// Clear is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_OperatorTrxCounter) Clear(fd protoreflect.FieldDescriptor) {
	switch fd.FullName() {
	case "chikku.egvmod.OperatorTrxCounter.operator":
		x.Operator = ""
	case "chikku.egvmod.OperatorTrxCounter.trx_count":
		x.TrxCount = int64(0)
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: chikku.egvmod.OperatorTrxCounter"))
		}
		panic(fmt.Errorf("message chikku.egvmod.OperatorTrxCounter does not contain field %s", fd.FullName()))
	}
}

// Get retrieves the value for a field.
//
// For unpopulated scalars, it returns the default value, where
// the default value of a bytes scalar is guaranteed to be a copy.
// For unpopulated composite types, it returns an empty, read-only view
// of the value; to obtain a mutable reference, use Mutable.
func (x *fastReflection_OperatorTrxCounter) Get(descriptor protoreflect.FieldDescriptor) protoreflect.Value {
	switch descriptor.FullName() {
	case "chikku.egvmod.OperatorTrxCounter.operator":
		value := x.Operator
		return protoreflect.ValueOfString(value)
	case "chikku.egvmod.OperatorTrxCounter.trx_count":
		value := x.TrxCount
		return protoreflect.ValueOfInt64(value)
	default:
		if descriptor.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: chikku.egvmod.OperatorTrxCounter"))
		}
		panic(fmt.Errorf("message chikku.egvmod.OperatorTrxCounter does not contain field %s", descriptor.FullName()))
	}
}

// Set stores the value for a field.
//
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType.
// When setting a composite type, it is unspecified whether the stored value
// aliases the source's memory in any way. If the composite value is an
// empty, read-only value, then it panics.
//
// Set is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_OperatorTrxCounter) Set(fd protoreflect.FieldDescriptor, value protoreflect.Value) {
	switch fd.FullName() {
	case "chikku.egvmod.OperatorTrxCounter.operator":
		x.Operator = value.Interface().(string)
	case "chikku.egvmod.OperatorTrxCounter.trx_count":
		x.TrxCount = value.Int()
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: chikku.egvmod.OperatorTrxCounter"))
		}
		panic(fmt.Errorf("message chikku.egvmod.OperatorTrxCounter does not contain field %s", fd.FullName()))
	}
}

// Mutable returns a mutable reference to a composite type.
//
// If the field is unpopulated, it may allocate a composite value.
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType
// if not already stored.
// It panics if the field does not contain a composite type.
//
// Mutable is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_OperatorTrxCounter) Mutable(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "chikku.egvmod.OperatorTrxCounter.operator":
		panic(fmt.Errorf("field operator of message chikku.egvmod.OperatorTrxCounter is not mutable"))
	case "chikku.egvmod.OperatorTrxCounter.trx_count":
		panic(fmt.Errorf("field trx_count of message chikku.egvmod.OperatorTrxCounter is not mutable"))
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: chikku.egvmod.OperatorTrxCounter"))
		}
		panic(fmt.Errorf("message chikku.egvmod.OperatorTrxCounter does not contain field %s", fd.FullName()))
	}
}

// NewField returns a new value that is assignable to the field
// for the given descriptor. For scalars, this returns the default value.
// For lists, maps, and messages, this returns a new, empty, mutable value.
func (x *fastReflection_OperatorTrxCounter) NewField(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "chikku.egvmod.OperatorTrxCounter.operator":
		return protoreflect.ValueOfString("")
	case "chikku.egvmod.OperatorTrxCounter.trx_count":
		return protoreflect.ValueOfInt64(int64(0))
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: chikku.egvmod.OperatorTrxCounter"))
		}
		panic(fmt.Errorf("message chikku.egvmod.OperatorTrxCounter does not contain field %s", fd.FullName()))
	}
}

// WhichOneof reports which field within the oneof is populated,
// returning nil if none are populated.
// It panics if the oneof descriptor does not belong to this message.
func (x *fastReflection_OperatorTrxCounter) WhichOneof(d protoreflect.OneofDescriptor) protoreflect.FieldDescriptor {
	switch d.FullName() {
	default:
		panic(fmt.Errorf("%s is not a oneof field in chikku.egvmod.OperatorTrxCounter", d.FullName()))
	}
	panic("unreachable")
}

// GetUnknown retrieves the entire list of unknown fields.
// The caller may only mutate the contents of the RawFields
// if the mutated bytes are stored back into the message with SetUnknown.
func (x *fastReflection_OperatorTrxCounter) GetUnknown() protoreflect.RawFields {
	return x.unknownFields
}

// SetUnknown stores an entire list of unknown fields.
// The raw fields must be syntactically valid according to the wire format.
// An implementation may panic if this is not the case.
// Once stored, the caller must not mutate the content of the RawFields.
// An empty RawFields may be passed to clear the fields.
//
// SetUnknown is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_OperatorTrxCounter) SetUnknown(fields protoreflect.RawFields) {
	x.unknownFields = fields
}

// IsValid reports whether the message is valid.
//
// An invalid message is an empty, read-only value.
//
// An invalid message often corresponds to a nil pointer of the concrete
// message type, but the details are implementation dependent.
// Validity is not part of the protobuf data model, and may not
// be preserved in marshaling or other operations.
func (x *fastReflection_OperatorTrxCounter) IsValid() bool {
	return x != nil
}

// ProtoMethods returns optional fastReflectionFeature-path implementations of various operations.
// This method may return nil.
//
// The returned methods type is identical to
// "google.golang.org/protobuf/runtime/protoiface".Methods.
// Consult the protoiface package documentation for details.
func (x *fastReflection_OperatorTrxCounter) ProtoMethods() *protoiface.Methods {
	size := func(input protoiface.SizeInput) protoiface.SizeOutput {
		x := input.Message.Interface().(*OperatorTrxCounter)
		if x == nil {
			return protoiface.SizeOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Size:              0,
			}
		}
		options := runtime.SizeInputToOptions(input)
		_ = options
		var n int
		var l int
		_ = l
		l = len(x.Operator)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.TrxCount != 0 {
			n += 1 + runtime.Sov(uint64(x.TrxCount))
		}
		if x.unknownFields != nil {
			n += len(x.unknownFields)
		}
		return protoiface.SizeOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Size:              n,
		}
	}

	marshal := func(input protoiface.MarshalInput) (protoiface.MarshalOutput, error) {
		x := input.Message.Interface().(*OperatorTrxCounter)
		if x == nil {
			return protoiface.MarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Buf:               input.Buf,
			}, nil
		}
		options := runtime.MarshalInputToOptions(input)
		_ = options
		size := options.Size(x)
		dAtA := make([]byte, size)
		i := len(dAtA)
		_ = i
		var l int
		_ = l
		if x.unknownFields != nil {
			i -= len(x.unknownFields)
			copy(dAtA[i:], x.unknownFields)
		}
		if x.TrxCount != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.TrxCount))
			i--
			dAtA[i] = 0x10
		}
		if len(x.Operator) > 0 {
			i -= len(x.Operator)
			copy(dAtA[i:], x.Operator)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Operator)))
			i--
			dAtA[i] = 0xa
		}
		if input.Buf != nil {
			input.Buf = append(input.Buf, dAtA...)
		} else {
			input.Buf = dAtA
		}
		return protoiface.MarshalOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Buf:               input.Buf,
		}, nil
	}
	unmarshal := func(input protoiface.UnmarshalInput) (protoiface.UnmarshalOutput, error) {
		x := input.Message.Interface().(*OperatorTrxCounter)
		if x == nil {
			return protoiface.UnmarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Flags:             input.Flags,
			}, nil
		}
		options := runtime.UnmarshalInputToOptions(input)
		_ = options
		dAtA := input.Buf
		l := len(dAtA)
		iNdEx := 0
		for iNdEx < l {
			preIndex := iNdEx
			var wire uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
				}
				if iNdEx >= l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				wire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			fieldNum := int32(wire >> 3)
			wireType := int(wire & 0x7)
			if wireType == 4 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: OperatorTrxCounter: wiretype end group for non-group")
			}
			if fieldNum <= 0 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: OperatorTrxCounter: illegal tag %d (wire type %d)", fieldNum, wire)
			}
			switch fieldNum {
			case 1:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Operator", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Operator = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 2:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field TrxCount", wireType)
				}
				x.TrxCount = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.TrxCount |= int64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			default:
				iNdEx = preIndex
				skippy, err := runtime.Skip(dAtA[iNdEx:])
				if err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				if (skippy < 0) || (iNdEx+skippy) < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if (iNdEx + skippy) > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if !options.DiscardUnknown {
					x.unknownFields = append(x.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
				}
				iNdEx += skippy
			}
		}

		if iNdEx > l {
			return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
		}
		return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, nil
	}
	return &protoiface.Methods{
		NoUnkeyedLiterals: struct{}{},
		Flags:             protoiface.SupportMarshalDeterministic | protoiface.SupportUnmarshalDiscardUnknown,
		Size:              size,
		Marshal:           marshal,
		Unmarshal:         unmarshal,
		Merge:             nil,
		CheckInitialized:  nil,
	}
}

var _ protoreflect.List = (*_OperatorsTrxsCount_2_list)(nil)

type _OperatorsTrxsCount_2_list struct {
	list *[]*OperatorTrxCounter
}

func (x *_OperatorsTrxsCount_2_list) Len() int {
	if x.list == nil {
		return 0
	}
	return len(*x.list)
}

func (x *_OperatorsTrxsCount_2_list) Get(i int) protoreflect.Value {
	return protoreflect.ValueOfMessage((*x.list)[i].ProtoReflect())
}

func (x *_OperatorsTrxsCount_2_list) Set(i int, value protoreflect.Value) {
	valueUnwrapped := value.Message()
	concreteValue := valueUnwrapped.Interface().(*OperatorTrxCounter)
	(*x.list)[i] = concreteValue
}

func (x *_OperatorsTrxsCount_2_list) Append(value protoreflect.Value) {
	valueUnwrapped := value.Message()
	concreteValue := valueUnwrapped.Interface().(*OperatorTrxCounter)
	*x.list = append(*x.list, concreteValue)
}

func (x *_OperatorsTrxsCount_2_list) AppendMutable() protoreflect.Value {
	v := new(OperatorTrxCounter)
	*x.list = append(*x.list, v)
	return protoreflect.ValueOfMessage(v.ProtoReflect())
}

func (x *_OperatorsTrxsCount_2_list) Truncate(n int) {
	for i := n; i < len(*x.list); i++ {
		(*x.list)[i] = nil
	}
	*x.list = (*x.list)[:n]
}

func (x *_OperatorsTrxsCount_2_list) NewElement() protoreflect.Value {
	v := new(OperatorTrxCounter)
	return protoreflect.ValueOfMessage(v.ProtoReflect())
}

func (x *_OperatorsTrxsCount_2_list) IsValid() bool {
	return x.list != nil
}

var (
	md_OperatorsTrxsCount                       protoreflect.MessageDescriptor
	fd_OperatorsTrxsCount_block_height          protoreflect.FieldDescriptor
	fd_OperatorsTrxsCount_operator_trx_counters protoreflect.FieldDescriptor
	fd_OperatorsTrxsCount_trx_count             protoreflect.FieldDescriptor
)

func init() {
	file_chikku_egvmod_trxcounter_proto_init()
	md_OperatorsTrxsCount = File_chikku_egvmod_trxcounter_proto.Messages().ByName("OperatorsTrxsCount")
	fd_OperatorsTrxsCount_block_height = md_OperatorsTrxsCount.Fields().ByName("block_height")
	fd_OperatorsTrxsCount_operator_trx_counters = md_OperatorsTrxsCount.Fields().ByName("operator_trx_counters")
	fd_OperatorsTrxsCount_trx_count = md_OperatorsTrxsCount.Fields().ByName("trx_count")
}

var _ protoreflect.Message = (*fastReflection_OperatorsTrxsCount)(nil)

type fastReflection_OperatorsTrxsCount OperatorsTrxsCount

func (x *OperatorsTrxsCount) ProtoReflect() protoreflect.Message {
	return (*fastReflection_OperatorsTrxsCount)(x)
}

func (x *OperatorsTrxsCount) slowProtoReflect() protoreflect.Message {
	mi := &file_chikku_egvmod_trxcounter_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

var _fastReflection_OperatorsTrxsCount_messageType fastReflection_OperatorsTrxsCount_messageType
var _ protoreflect.MessageType = fastReflection_OperatorsTrxsCount_messageType{}

type fastReflection_OperatorsTrxsCount_messageType struct{}

func (x fastReflection_OperatorsTrxsCount_messageType) Zero() protoreflect.Message {
	return (*fastReflection_OperatorsTrxsCount)(nil)
}
func (x fastReflection_OperatorsTrxsCount_messageType) New() protoreflect.Message {
	return new(fastReflection_OperatorsTrxsCount)
}
func (x fastReflection_OperatorsTrxsCount_messageType) Descriptor() protoreflect.MessageDescriptor {
	return md_OperatorsTrxsCount
}

// Descriptor returns message descriptor, which contains only the protobuf
// type information for the message.
func (x *fastReflection_OperatorsTrxsCount) Descriptor() protoreflect.MessageDescriptor {
	return md_OperatorsTrxsCount
}

// Type returns the message type, which encapsulates both Go and protobuf
// type information. If the Go type information is not needed,
// it is recommended that the message descriptor be used instead.
func (x *fastReflection_OperatorsTrxsCount) Type() protoreflect.MessageType {
	return _fastReflection_OperatorsTrxsCount_messageType
}

// New returns a newly allocated and mutable empty message.
func (x *fastReflection_OperatorsTrxsCount) New() protoreflect.Message {
	return new(fastReflection_OperatorsTrxsCount)
}

// Interface unwraps the message reflection interface and
// returns the underlying ProtoMessage interface.
func (x *fastReflection_OperatorsTrxsCount) Interface() protoreflect.ProtoMessage {
	return (*OperatorsTrxsCount)(x)
}

// Range iterates over every populated field in an undefined order,
// calling f for each field descriptor and value encountered.
// Range returns immediately if f returns false.
// While iterating, mutating operations may only be performed
// on the current field descriptor.
func (x *fastReflection_OperatorsTrxsCount) Range(f func(protoreflect.FieldDescriptor, protoreflect.Value) bool) {
	if x.BlockHeight != int64(0) {
		value := protoreflect.ValueOfInt64(x.BlockHeight)
		if !f(fd_OperatorsTrxsCount_block_height, value) {
			return
		}
	}
	if len(x.OperatorTrxCounters) != 0 {
		value := protoreflect.ValueOfList(&_OperatorsTrxsCount_2_list{list: &x.OperatorTrxCounters})
		if !f(fd_OperatorsTrxsCount_operator_trx_counters, value) {
			return
		}
	}
	if x.TrxCount != int64(0) {
		value := protoreflect.ValueOfInt64(x.TrxCount)
		if !f(fd_OperatorsTrxsCount_trx_count, value) {
			return
		}
	}
}

// Has reports whether a field is populated.
//
// Some fields have the property of nullability where it is possible to
// distinguish between the default value of a field and whether the field
// was explicitly populated with the default value. Singular message fields,
// member fields of a oneof, and proto2 scalar fields are nullable. Such
// fields are populated only if explicitly set.
//
// In other cases (aside from the nullable cases above),
// a proto3 scalar field is populated if it contains a non-zero value, and
// a repeated field is populated if it is non-empty.
func (x *fastReflection_OperatorsTrxsCount) Has(fd protoreflect.FieldDescriptor) bool {
	switch fd.FullName() {
	case "chikku.egvmod.OperatorsTrxsCount.block_height":
		return x.BlockHeight != int64(0)
	case "chikku.egvmod.OperatorsTrxsCount.operator_trx_counters":
		return len(x.OperatorTrxCounters) != 0
	case "chikku.egvmod.OperatorsTrxsCount.trx_count":
		return x.TrxCount != int64(0)
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: chikku.egvmod.OperatorsTrxsCount"))
		}
		panic(fmt.Errorf("message chikku.egvmod.OperatorsTrxsCount does not contain field %s", fd.FullName()))
	}
}

// Clear clears the field such that a subsequent Has call reports false.
//
// Clearing an extension field clears both the extension type and value
// associated with the given field number.
//
// Clear is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_OperatorsTrxsCount) Clear(fd protoreflect.FieldDescriptor) {
	switch fd.FullName() {
	case "chikku.egvmod.OperatorsTrxsCount.block_height":
		x.BlockHeight = int64(0)
	case "chikku.egvmod.OperatorsTrxsCount.operator_trx_counters":
		x.OperatorTrxCounters = nil
	case "chikku.egvmod.OperatorsTrxsCount.trx_count":
		x.TrxCount = int64(0)
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: chikku.egvmod.OperatorsTrxsCount"))
		}
		panic(fmt.Errorf("message chikku.egvmod.OperatorsTrxsCount does not contain field %s", fd.FullName()))
	}
}

// Get retrieves the value for a field.
//
// For unpopulated scalars, it returns the default value, where
// the default value of a bytes scalar is guaranteed to be a copy.
// For unpopulated composite types, it returns an empty, read-only view
// of the value; to obtain a mutable reference, use Mutable.
func (x *fastReflection_OperatorsTrxsCount) Get(descriptor protoreflect.FieldDescriptor) protoreflect.Value {
	switch descriptor.FullName() {
	case "chikku.egvmod.OperatorsTrxsCount.block_height":
		value := x.BlockHeight
		return protoreflect.ValueOfInt64(value)
	case "chikku.egvmod.OperatorsTrxsCount.operator_trx_counters":
		if len(x.OperatorTrxCounters) == 0 {
			return protoreflect.ValueOfList(&_OperatorsTrxsCount_2_list{})
		}
		listValue := &_OperatorsTrxsCount_2_list{list: &x.OperatorTrxCounters}
		return protoreflect.ValueOfList(listValue)
	case "chikku.egvmod.OperatorsTrxsCount.trx_count":
		value := x.TrxCount
		return protoreflect.ValueOfInt64(value)
	default:
		if descriptor.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: chikku.egvmod.OperatorsTrxsCount"))
		}
		panic(fmt.Errorf("message chikku.egvmod.OperatorsTrxsCount does not contain field %s", descriptor.FullName()))
	}
}

// Set stores the value for a field.
//
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType.
// When setting a composite type, it is unspecified whether the stored value
// aliases the source's memory in any way. If the composite value is an
// empty, read-only value, then it panics.
//
// Set is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_OperatorsTrxsCount) Set(fd protoreflect.FieldDescriptor, value protoreflect.Value) {
	switch fd.FullName() {
	case "chikku.egvmod.OperatorsTrxsCount.block_height":
		x.BlockHeight = value.Int()
	case "chikku.egvmod.OperatorsTrxsCount.operator_trx_counters":
		lv := value.List()
		clv := lv.(*_OperatorsTrxsCount_2_list)
		x.OperatorTrxCounters = *clv.list
	case "chikku.egvmod.OperatorsTrxsCount.trx_count":
		x.TrxCount = value.Int()
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: chikku.egvmod.OperatorsTrxsCount"))
		}
		panic(fmt.Errorf("message chikku.egvmod.OperatorsTrxsCount does not contain field %s", fd.FullName()))
	}
}

// Mutable returns a mutable reference to a composite type.
//
// If the field is unpopulated, it may allocate a composite value.
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType
// if not already stored.
// It panics if the field does not contain a composite type.
//
// Mutable is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_OperatorsTrxsCount) Mutable(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "chikku.egvmod.OperatorsTrxsCount.operator_trx_counters":
		if x.OperatorTrxCounters == nil {
			x.OperatorTrxCounters = []*OperatorTrxCounter{}
		}
		value := &_OperatorsTrxsCount_2_list{list: &x.OperatorTrxCounters}
		return protoreflect.ValueOfList(value)
	case "chikku.egvmod.OperatorsTrxsCount.block_height":
		panic(fmt.Errorf("field block_height of message chikku.egvmod.OperatorsTrxsCount is not mutable"))
	case "chikku.egvmod.OperatorsTrxsCount.trx_count":
		panic(fmt.Errorf("field trx_count of message chikku.egvmod.OperatorsTrxsCount is not mutable"))
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: chikku.egvmod.OperatorsTrxsCount"))
		}
		panic(fmt.Errorf("message chikku.egvmod.OperatorsTrxsCount does not contain field %s", fd.FullName()))
	}
}

// NewField returns a new value that is assignable to the field
// for the given descriptor. For scalars, this returns the default value.
// For lists, maps, and messages, this returns a new, empty, mutable value.
func (x *fastReflection_OperatorsTrxsCount) NewField(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "chikku.egvmod.OperatorsTrxsCount.block_height":
		return protoreflect.ValueOfInt64(int64(0))
	case "chikku.egvmod.OperatorsTrxsCount.operator_trx_counters":
		list := []*OperatorTrxCounter{}
		return protoreflect.ValueOfList(&_OperatorsTrxsCount_2_list{list: &list})
	case "chikku.egvmod.OperatorsTrxsCount.trx_count":
		return protoreflect.ValueOfInt64(int64(0))
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: chikku.egvmod.OperatorsTrxsCount"))
		}
		panic(fmt.Errorf("message chikku.egvmod.OperatorsTrxsCount does not contain field %s", fd.FullName()))
	}
}

// WhichOneof reports which field within the oneof is populated,
// returning nil if none are populated.
// It panics if the oneof descriptor does not belong to this message.
func (x *fastReflection_OperatorsTrxsCount) WhichOneof(d protoreflect.OneofDescriptor) protoreflect.FieldDescriptor {
	switch d.FullName() {
	default:
		panic(fmt.Errorf("%s is not a oneof field in chikku.egvmod.OperatorsTrxsCount", d.FullName()))
	}
	panic("unreachable")
}

// GetUnknown retrieves the entire list of unknown fields.
// The caller may only mutate the contents of the RawFields
// if the mutated bytes are stored back into the message with SetUnknown.
func (x *fastReflection_OperatorsTrxsCount) GetUnknown() protoreflect.RawFields {
	return x.unknownFields
}

// SetUnknown stores an entire list of unknown fields.
// The raw fields must be syntactically valid according to the wire format.
// An implementation may panic if this is not the case.
// Once stored, the caller must not mutate the content of the RawFields.
// An empty RawFields may be passed to clear the fields.
//
// SetUnknown is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_OperatorsTrxsCount) SetUnknown(fields protoreflect.RawFields) {
	x.unknownFields = fields
}

// IsValid reports whether the message is valid.
//
// An invalid message is an empty, read-only value.
//
// An invalid message often corresponds to a nil pointer of the concrete
// message type, but the details are implementation dependent.
// Validity is not part of the protobuf data model, and may not
// be preserved in marshaling or other operations.
func (x *fastReflection_OperatorsTrxsCount) IsValid() bool {
	return x != nil
}

// ProtoMethods returns optional fastReflectionFeature-path implementations of various operations.
// This method may return nil.
//
// The returned methods type is identical to
// "google.golang.org/protobuf/runtime/protoiface".Methods.
// Consult the protoiface package documentation for details.
func (x *fastReflection_OperatorsTrxsCount) ProtoMethods() *protoiface.Methods {
	size := func(input protoiface.SizeInput) protoiface.SizeOutput {
		x := input.Message.Interface().(*OperatorsTrxsCount)
		if x == nil {
			return protoiface.SizeOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Size:              0,
			}
		}
		options := runtime.SizeInputToOptions(input)
		_ = options
		var n int
		var l int
		_ = l
		if x.BlockHeight != 0 {
			n += 1 + runtime.Sov(uint64(x.BlockHeight))
		}
		if len(x.OperatorTrxCounters) > 0 {
			for _, e := range x.OperatorTrxCounters {
				l = options.Size(e)
				n += 1 + l + runtime.Sov(uint64(l))
			}
		}
		if x.TrxCount != 0 {
			n += 1 + runtime.Sov(uint64(x.TrxCount))
		}
		if x.unknownFields != nil {
			n += len(x.unknownFields)
		}
		return protoiface.SizeOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Size:              n,
		}
	}

	marshal := func(input protoiface.MarshalInput) (protoiface.MarshalOutput, error) {
		x := input.Message.Interface().(*OperatorsTrxsCount)
		if x == nil {
			return protoiface.MarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Buf:               input.Buf,
			}, nil
		}
		options := runtime.MarshalInputToOptions(input)
		_ = options
		size := options.Size(x)
		dAtA := make([]byte, size)
		i := len(dAtA)
		_ = i
		var l int
		_ = l
		if x.unknownFields != nil {
			i -= len(x.unknownFields)
			copy(dAtA[i:], x.unknownFields)
		}
		if x.TrxCount != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.TrxCount))
			i--
			dAtA[i] = 0x18
		}
		if len(x.OperatorTrxCounters) > 0 {
			for iNdEx := len(x.OperatorTrxCounters) - 1; iNdEx >= 0; iNdEx-- {
				encoded, err := options.Marshal(x.OperatorTrxCounters[iNdEx])
				if err != nil {
					return protoiface.MarshalOutput{
						NoUnkeyedLiterals: input.NoUnkeyedLiterals,
						Buf:               input.Buf,
					}, err
				}
				i -= len(encoded)
				copy(dAtA[i:], encoded)
				i = runtime.EncodeVarint(dAtA, i, uint64(len(encoded)))
				i--
				dAtA[i] = 0x12
			}
		}
		if x.BlockHeight != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.BlockHeight))
			i--
			dAtA[i] = 0x8
		}
		if input.Buf != nil {
			input.Buf = append(input.Buf, dAtA...)
		} else {
			input.Buf = dAtA
		}
		return protoiface.MarshalOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Buf:               input.Buf,
		}, nil
	}
	unmarshal := func(input protoiface.UnmarshalInput) (protoiface.UnmarshalOutput, error) {
		x := input.Message.Interface().(*OperatorsTrxsCount)
		if x == nil {
			return protoiface.UnmarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Flags:             input.Flags,
			}, nil
		}
		options := runtime.UnmarshalInputToOptions(input)
		_ = options
		dAtA := input.Buf
		l := len(dAtA)
		iNdEx := 0
		for iNdEx < l {
			preIndex := iNdEx
			var wire uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
				}
				if iNdEx >= l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				wire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			fieldNum := int32(wire >> 3)
			wireType := int(wire & 0x7)
			if wireType == 4 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: OperatorsTrxsCount: wiretype end group for non-group")
			}
			if fieldNum <= 0 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: OperatorsTrxsCount: illegal tag %d (wire type %d)", fieldNum, wire)
			}
			switch fieldNum {
			case 1:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field BlockHeight", wireType)
				}
				x.BlockHeight = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.BlockHeight |= int64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 2:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field OperatorTrxCounters", wireType)
				}
				var msglen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					msglen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if msglen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + msglen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.OperatorTrxCounters = append(x.OperatorTrxCounters, &OperatorTrxCounter{})
				if err := options.Unmarshal(dAtA[iNdEx:postIndex], x.OperatorTrxCounters[len(x.OperatorTrxCounters)-1]); err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				iNdEx = postIndex
			case 3:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field TrxCount", wireType)
				}
				x.TrxCount = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.TrxCount |= int64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			default:
				iNdEx = preIndex
				skippy, err := runtime.Skip(dAtA[iNdEx:])
				if err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				if (skippy < 0) || (iNdEx+skippy) < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if (iNdEx + skippy) > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if !options.DiscardUnknown {
					x.unknownFields = append(x.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
				}
				iNdEx += skippy
			}
		}

		if iNdEx > l {
			return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
		}
		return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, nil
	}
	return &protoiface.Methods{
		NoUnkeyedLiterals: struct{}{},
		Flags:             protoiface.SupportMarshalDeterministic | protoiface.SupportUnmarshalDiscardUnknown,
		Size:              size,
		Marshal:           marshal,
		Unmarshal:         unmarshal,
		Merge:             nil,
		CheckInitialized:  nil,
	}
}

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.0
// 	protoc        (unknown)
// source: chikku/egvmod/trxcounter.proto

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// OperatorTrxCounter defines the operator transaction counter.
type OperatorTrxCounter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Operator is the operator address.
	Operator string `protobuf:"bytes,1,opt,name=operator,proto3" json:"operator,omitempty"`
	// TrxCount is the transaction count.
	TrxCount int64 `protobuf:"varint,2,opt,name=trx_count,json=trxCount,proto3" json:"trx_count,omitempty"`
}

func (x *OperatorTrxCounter) Reset() {
	*x = OperatorTrxCounter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chikku_egvmod_trxcounter_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OperatorTrxCounter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperatorTrxCounter) ProtoMessage() {}

// Deprecated: Use OperatorTrxCounter.ProtoReflect.Descriptor instead.
func (*OperatorTrxCounter) Descriptor() ([]byte, []int) {
	return file_chikku_egvmod_trxcounter_proto_rawDescGZIP(), []int{0}
}

func (x *OperatorTrxCounter) GetOperator() string {
	if x != nil {
		return x.Operator
	}
	return ""
}

func (x *OperatorTrxCounter) GetTrxCount() int64 {
	if x != nil {
		return x.TrxCount
	}
	return 0
}

// OperatosTrxsCount defines the operators transaction count.
type OperatorsTrxsCount struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BlockHeight int64 `protobuf:"varint,1,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
	// OperatorTrxCount is the operator transaction count.
	OperatorTrxCounters []*OperatorTrxCounter `protobuf:"bytes,2,rep,name=operator_trx_counters,json=operatorTrxCounters,proto3" json:"operator_trx_counters,omitempty"`
	// TrxCount is the transaction count.
	TrxCount int64 `protobuf:"varint,3,opt,name=trx_count,json=trxCount,proto3" json:"trx_count,omitempty"`
}

func (x *OperatorsTrxsCount) Reset() {
	*x = OperatorsTrxsCount{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chikku_egvmod_trxcounter_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OperatorsTrxsCount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperatorsTrxsCount) ProtoMessage() {}

// Deprecated: Use OperatorsTrxsCount.ProtoReflect.Descriptor instead.
func (*OperatorsTrxsCount) Descriptor() ([]byte, []int) {
	return file_chikku_egvmod_trxcounter_proto_rawDescGZIP(), []int{1}
}

func (x *OperatorsTrxsCount) GetBlockHeight() int64 {
	if x != nil {
		return x.BlockHeight
	}
	return 0
}

func (x *OperatorsTrxsCount) GetOperatorTrxCounters() []*OperatorTrxCounter {
	if x != nil {
		return x.OperatorTrxCounters
	}
	return nil
}

func (x *OperatorsTrxsCount) GetTrxCount() int64 {
	if x != nil {
		return x.TrxCount
	}
	return 0
}

var File_chikku_egvmod_trxcounter_proto protoreflect.FileDescriptor

var file_chikku_egvmod_trxcounter_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x63, 0x68, 0x69, 0x6b, 0x6b, 0x75, 0x2f, 0x65, 0x67, 0x76, 0x6d, 0x6f, 0x64, 0x2f,
	0x74, 0x72, 0x78, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0d, 0x63, 0x68, 0x69, 0x6b, 0x6b, 0x75, 0x2e, 0x65, 0x67, 0x76, 0x6d, 0x6f, 0x64, 0x1a,
	0x14, 0x67, 0x6f, 0x67, 0x6f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x6f, 0x67, 0x6f, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x69, 0x0a, 0x12, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f,
	0x72, 0x54, 0x72, 0x78, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x12, 0x28, 0x0a, 0x08, 0x6f,
	0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x0c, 0xe2,
	0xde, 0x1f, 0x08, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x52, 0x08, 0x6f, 0x70, 0x65,
	0x72, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x29, 0x0a, 0x09, 0x74, 0x72, 0x78, 0x5f, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x42, 0x0c, 0xe2, 0xde, 0x1f, 0x08, 0x54, 0x72,
	0x78, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x08, 0x74, 0x72, 0x78, 0x43, 0x6f, 0x75, 0x6e, 0x74,
	0x22, 0xe3, 0x01, 0x0a, 0x12, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x73, 0x54, 0x72,
	0x78, 0x73, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x32, 0x0a, 0x0c, 0x62, 0x6c, 0x6f, 0x63, 0x6b,
	0x5f, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x42, 0x0f, 0xe2,
	0xde, 0x1f, 0x0b, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x52, 0x0b,
	0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x6e, 0x0a, 0x15, 0x6f,
	0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x5f, 0x74, 0x72, 0x78, 0x5f, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x63, 0x68, 0x69,
	0x6b, 0x6b, 0x75, 0x2e, 0x65, 0x67, 0x76, 0x6d, 0x6f, 0x64, 0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61,
	0x74, 0x6f, 0x72, 0x54, 0x72, 0x78, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x42, 0x17, 0xe2,
	0xde, 0x1f, 0x13, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x54, 0x72, 0x78, 0x43, 0x6f,
	0x75, 0x6e, 0x74, 0x65, 0x72, 0x73, 0x52, 0x13, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72,
	0x54, 0x72, 0x78, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x73, 0x12, 0x29, 0x0a, 0x09, 0x74,
	0x72, 0x78, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x42, 0x0c,
	0xe2, 0xde, 0x1f, 0x08, 0x54, 0x72, 0x78, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x08, 0x74, 0x72,
	0x78, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x42, 0x93, 0x01, 0x0a, 0x11, 0x63, 0x6f, 0x6d, 0x2e, 0x63,
	0x68, 0x69, 0x6b, 0x6b, 0x75, 0x2e, 0x65, 0x67, 0x76, 0x6d, 0x6f, 0x64, 0x42, 0x0f, 0x54, 0x72,
	0x78, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a,
	0x18, 0x63, 0x68, 0x69, 0x6b, 0x6b, 0x75, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x68, 0x69, 0x6b,
	0x6b, 0x75, 0x2f, 0x65, 0x67, 0x76, 0x6d, 0x6f, 0x64, 0xa2, 0x02, 0x03, 0x43, 0x45, 0x58, 0xaa,
	0x02, 0x0d, 0x43, 0x68, 0x69, 0x6b, 0x6b, 0x75, 0x2e, 0x45, 0x67, 0x76, 0x6d, 0x6f, 0x64, 0xca,
	0x02, 0x0d, 0x43, 0x68, 0x69, 0x6b, 0x6b, 0x75, 0x5c, 0x45, 0x67, 0x76, 0x6d, 0x6f, 0x64, 0xe2,
	0x02, 0x19, 0x43, 0x68, 0x69, 0x6b, 0x6b, 0x75, 0x5c, 0x45, 0x67, 0x76, 0x6d, 0x6f, 0x64, 0x5c,
	0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x0e, 0x43, 0x68,
	0x69, 0x6b, 0x6b, 0x75, 0x3a, 0x3a, 0x45, 0x67, 0x76, 0x6d, 0x6f, 0x64, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_chikku_egvmod_trxcounter_proto_rawDescOnce sync.Once
	file_chikku_egvmod_trxcounter_proto_rawDescData = file_chikku_egvmod_trxcounter_proto_rawDesc
)

func file_chikku_egvmod_trxcounter_proto_rawDescGZIP() []byte {
	file_chikku_egvmod_trxcounter_proto_rawDescOnce.Do(func() {
		file_chikku_egvmod_trxcounter_proto_rawDescData = protoimpl.X.CompressGZIP(file_chikku_egvmod_trxcounter_proto_rawDescData)
	})
	return file_chikku_egvmod_trxcounter_proto_rawDescData
}

var file_chikku_egvmod_trxcounter_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_chikku_egvmod_trxcounter_proto_goTypes = []interface{}{
	(*OperatorTrxCounter)(nil), // 0: chikku.egvmod.OperatorTrxCounter
	(*OperatorsTrxsCount)(nil), // 1: chikku.egvmod.OperatorsTrxsCount
}
var file_chikku_egvmod_trxcounter_proto_depIdxs = []int32{
	0, // 0: chikku.egvmod.OperatorsTrxsCount.operator_trx_counters:type_name -> chikku.egvmod.OperatorTrxCounter
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_chikku_egvmod_trxcounter_proto_init() }
func file_chikku_egvmod_trxcounter_proto_init() {
	if File_chikku_egvmod_trxcounter_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_chikku_egvmod_trxcounter_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OperatorTrxCounter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chikku_egvmod_trxcounter_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OperatorsTrxsCount); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_chikku_egvmod_trxcounter_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_chikku_egvmod_trxcounter_proto_goTypes,
		DependencyIndexes: file_chikku_egvmod_trxcounter_proto_depIdxs,
		MessageInfos:      file_chikku_egvmod_trxcounter_proto_msgTypes,
	}.Build()
	File_chikku_egvmod_trxcounter_proto = out.File
	file_chikku_egvmod_trxcounter_proto_rawDesc = nil
	file_chikku_egvmod_trxcounter_proto_goTypes = nil
	file_chikku_egvmod_trxcounter_proto_depIdxs = nil
}
